### ISSUE TITLE
Named arguments issue

### ISSUE THREAD

**Issue by vicb** [angular/clang-format#10]
in ng2, api.ts:

``` ts
  constructor({
      id, selector, compileChildren, events, hostListeners, hostProperties,
      hostAttributes, hostActions, properties, readAttributes, type,
      callOnDestroy, callOnChange, callOnAllChangesDone,
      changeDetection
    }:{
      id?:string, selector?:string, compileChildren?:boolean, events?:List<string>, hostListeners?:Map<string, string>, hostProperties?:Map<string, string>,
      hostAttributes?:Map<string, string>, hostActions?:Map<string, string>, properties?:Map<string, string>, readAttributes?:List<string>, type?:number,
      callOnDestroy?:boolean, callOnChange?:boolean, callOnAllChangesDone?:boolean,
      changeDetection?:string
    }) {
```

The 100 char limit is not respected 

/cc @mprobst

**Comment by mprobst** [comment]
I think `clang-format` currently gives up on type declarations that are overlong, I'll have to TAL.

But irregardless, this looks to me as if the real fix was to not have such a complex constructor definition, but rather all these arguments structured into objects, and maybe extract an interface and give it types.

**Comment by vicb** [comment]
isn't the real issue that clang-format does not understand the syntax ?

see https://github.com/angular/angular/blob/8609543ad0fb2820d5b8ca77e03af65973fd0f6c/modules/angular2/src/core/annotations_impl/annotations.ts#L754

**Comment by mprobst** [comment]
@vicb sure, clang-format should handle this case (it was misunderstanding it as a ternary operator). But this syntax also really seems overly complicated.

**Comment by vicb** [comment]
@mprobst do you have a better suggestion to handle named parameters ?

**Comment by mprobst** [comment]
@vicb you can extract one or more interfaces for the named parameters you're taking:

``` ts
interface FooParams { a?; b?; c?; }
function Foo({a, b, c}: FooParams) {}
```

But admittedly that's not very nice either.

**Comment by mprobst** [comment]
This is fixed.
