### ISSUE TITLE
problems with large deeply nested test file

### ISSUE THREAD

**Issue by tbosch** [angular/clang-format#11]
This attached file gets more spaces on every run. If I remove an `it` block, it is formatted correctly.

**Comment by tbosch** [comment]
https://gist.github.com/tbosch/9cefcc30196e00509036

**Comment by tbosch** [comment]
Also, `clang-format` takes pretty long to format this (about 20seconds).

**Comment by mprobst** [comment]
This has been fixed a while ago.
