### ISSUE TITLE
enum formatting

### ISSUE THREAD

**Issue by vicb** [angular/clang-format#14]
```
enum TokenType {
  CHARACTER,
  IDENTIFIER,
  KEYWORD,
  STRING,
  OPERATOR,
  NUMBER
}

@Injectable() export class Lexer {
} 
```

should be

```
enum TokenType {
  CHARACTER,
  IDENTIFIER,
  KEYWORD,
  STRING,
  OPERATOR,
  NUMBER
}

@Injectable() 
export class Lexer {
} 
```

Most probably caused because there is ";" after the enum - it would cause Dart to fail.

/cc @mprobst

**Comment by vicb** [comment]
Actually this should rather be a bug on ts2dart as TypeScript enum can have a ";"

**Comment by mprobst** [comment]
No, this is a valid `clang-format` issue. `enum` declarations do not need a trailing semicolon in TypeScript, and `clang-format` incorrectly doesn't terminate the current line after one.

**Comment by mprobst** [comment]
Sent out http://reviews.llvm.org/D10485.

**Comment by vicb** [comment]
:+1: 

We should still fix ts2dart to remove the optional ";", right ?

**Comment by mprobst** [comment]
`clang-format` never removes tokens, it only remodels whitespace. Your `;` will just end up as an empty statement in the code, on its own line, so it'll be easy enough to remove.

**Comment by mprobst** [comment]
As discussed offline, `enum X { Y, Z }` should not be followed by a semicolon, so the `ts2dart` translation is fine.

The formatting patch has been submitted, closing this issue.
