### ISSUE TITLE
Allow wildcards (globbing)

### ISSUE THREAD

**Issue by alexeagle** [angular/clang-format#21]
Currently, the gulp-clang-format plugin is our method to allow globbing all the files under a project.
If this fails (in checked-diff mode), it prints a command allowing us to re-format the correct files.

However, it's convenient to have a command-line which can be run to re-format everything in the project. The native clang-format binary doesn't support this (no way to expand nested directories in shell). But our wrapper could.

Then we could do something like
`package.json`: `scripts: { 'format': 'clang-format -i' }`
and `npm run format` would give the right versions and config for everything.

**Comment by mprobst** [comment]
I recently changed `gulp-clang-format` to work by using the tree diff plugin. Part of that effort is that we can now `clang-format` entire trees in a gulp pipe. It should be reasonably easy to write a gulp task to format all files in the project.

But I agree, `npm run clang-format` would be nice, too.

**Comment by filipesilva** [comment]
I've added a PR that enables globbing. 

It's something I'd like to use for `angular-cli` without having to use `gulp-clang-format`.

**Comment by alexeagle** [comment]
Now available in 1.0.35
