### ISSUE TITLE
allow nodejs shebang for 'bin' file

### ISSUE THREAD

**Issue by alexeagle** [angular/clang-format#28]
In this very repo, there is a "bin":"index.js" in package.json

Running clang-format breaks that line.

```
clang-format alexeagle$ clang-format index.js
#!/usr/bin / env node
```

this doesn't work anymore for execution in a shell, of course.

**Comment by alexeagle** [comment]
and `// clang-format off` doesn't work since it has to be on the first line, according to the typescript compiler:

```
$ ./node_modules/.bin/tsc -p tools/compiler_cli/src -w
tools/compiler_cli/src/main.ts(2,1): error TS1127: Invalid character.
tools/compiler_cli/src/main.ts(2,16): error TS1005: ';' expected.
```

**Comment by mprobst** [comment]
This has been fixed.

**Comment by mwgkgk** [comment]
Hey, clang-format version 10.0.1 here,

Another situation with shebang, this time with [Cling](https://github.com/root-project/cling) - the project advertises the shebang on its [homepage](https://cdn.rawgit.com/root-project/cling/master/www/index.html). It gets mauled by clang-format and I don't see the [option](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) to have the offset set locally with `.clang-format`, so we're left with `--offset=<uint>`, which is not the best approach to use when calling clang-format automatically from the editor, as we'd need a wrapper to detect the offset.

**Comment by mprobst** [comment]
I think we're only allowing the shebang for TS and JS files. If you need
that for C++, you'll need to file an upstream clang-format bug with LLVM.
