### ISSUE TITLE
Spaces in import statements

### ISSUE THREAD

**Issue by juergenzimmermann** [angular/clang-format#29]
clang-format wants import statements to look like this one:

```
import {ObjectID} from 'mongodb';
```

However, the Angular style guide https://angular.io/docs/ts/latest/guide/style-guide.html recommends to use _spaces_:

```
import { ObjectID } from 'mongodb';
```

**Comment by mprobst** [comment]
I think that's not a recommendation in the Angular style guide - the Angular style guide is not about formatting, more about how to structure your code.

Angular 2 does actually use clang-format, and if you check its source, you'll see it doesn't use whitespace within the import curlies.
