### ISSUE TITLE
Formatting of ternary operator incorrect in some contexts

### ISSUE THREAD

**Issue by jbms** [angular/clang-format#32]
When ternary expressions are used in TypeScript class variable default initializers or in TypeScript/JavaScript class method parameter default initializers, no space is inserted before the `?` 
and before the `:`:

Actual output: (clang-format NPM version 1.0.41)

``` typescript
const z = true ? 1 : 2;
function foo(a = true ? 1 : 2) {}
class Foo {
  b = true? 1: 2;
  method(a = true? 1: 2) {}
};
```

Expected output:

``` typescript
const z = true ? 1 : 2;
function foo(a = true ? 1 : 2) {}
class Foo {
  b = true ? 1 : 2;
  method(a = true ? 1 : 2) {}
};
```

**Comment by mprobst** [comment]
This is fixed upstream in http://reviews.llvm.org/D21658, pending a release.
