### ISSUE TITLE
Push new release that includes non-null assertion operator fix.

### ISSUE THREAD

**Issue by jbms** [angular/clang-format#33]
It would be great if you could publish a new version of this package that includes clang revision 272524 with your post-fix non-null assertion operator fix, since this seriously affects the usability of clang-format with code that contains non-null assertion operators.

**Comment by mprobst** [comment]
Working on it. Somehow our windows builder machine no longer builds clang-format. Will take a bit.

**Comment by mprobst** [comment]
Done, 1.0.42.
