### ISSUE TITLE
Possible speed boost ?

### ISSUE THREAD

**Issue by vicb** [angular/clang-format#37]
While running gulp format on angular, it seems like a lot of files get written.

Does that mean that every single files gets overwritten whether it has been "formatted" or not ?
If this is the case it should be possible to speed up the process by writing to disk only the files that have been modified.

**Comment by mprobst** [comment]
I think if anything this is a problem with the gulp integration? Note that disk writes are pretty cheap as long as you don't flush the file storage, not sure if it'd have a lot of impact.

**Comment by vicb** [comment]
yep definitely a pb with gulp integration

there is the added cost of triggering watchers.
