### ISSUE TITLE
Union / intersection type formatting are inconsistent

### ISSUE THREAD

**Issue by vicb** [angular/clang-format#38]
On the angular repo:

``` ts
export function getPluralCase(locale: string, nLike: number | string): Plural { ...
```

vs

``` ts
export const Inject: typeof InjectMetadata&InjectMetadataCtor = ...
```

I find the readability in the later case much worse (@mpbrost seems prefer this way)
- make it consistent,
- make it configurable

/ref https://github.com/angular/angular/pull/11507/files#r78282320

**Comment by vicb** [comment]
FWIW the TS spec uses spaces, see https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3.4

**Comment by mprobst** [comment]
I think you have an outdated version, the `function` type above formats w/o space around the `|`.

As for having spaces around the `|` in types, this is Working As Intended, to make `Foo|null` more readable. I think intersection types are very rare, and for union types there is enough whitespace around the `|` char. YMMV.

**Comment by vicb** [comment]
WS have indeed been removed in the last version... but it's not configurable, is it ?

**Comment by mprobst** [comment]
Nope, isn't. I'm a bit hesitant to add more options, I'm not sure how much
of a problem this really is in practice.
