### ISSUE TITLE
Wrong formatting 

### ISSUE THREAD

**Issue by vicb** [angular/clang-format#39]
``` ts
export interface ViewChildrenDecorator {
  /**
   * @docsNotRequired
 */ (selector: Type<any>|Function|string, {read}?: {read?: any}): any;
  new (selector: Type<any>|Function|string, {read}?: {read?: any}): ViewChildren;
}
```

Notice the doc for the `(...)` call.

Would be worth checking how docs are rendered on `[Symbol]()` also

**Comment by mprobst** [comment]
Cannot reproduce with the current clang-format version.

Note that this is one of the rare places where clang-format depends a bit on the input formatting - if you don't have a line break between the doc comment and the method, it will not insert one (thinking that you intentionally want this to be a start-of-the-line comment).
