### ISSUE TITLE
Incorrect format for a type with template followed by an equals sign.

### ISSUE THREAD

**Issue by Goodwine** [angular/clang-format#46]
When a template thingy is followed by an equals sign, clang-format thinks it's a `less-than-or-equal-to` operator and formats things weird.

This

```ts
class Something<T> {};

let a: Something<string>=new Something<string>();
let b: Something<string> =new Something<string>();
```

becomes this

```ts
class Something<T> {};

let a: Something < string >= new Something<string>();
let b: Something<string> = new Something<string>();
```

**Comment by mprobst** [comment]
Known issue. I'm actually quite surprised this is valid TS to begin with, unparsing the `>=` into separate tokens is tricky. This is too hard to fix for us, as we cannot know when to split `>=` before actual parsing, which is way too late in the tool stage. My suggestion is not to write code like that :-)
