### ISSUE TITLE
npm dist-tag latest is 1.0.41-b

### ISSUE THREAD

**Issue by bgotink** [angular/clang-format#52]
The npm `latest` dist-tag is currently `1.0.41-b`, but there are already versions higher than 1.0.41.
Is this by design&mdash;i.e. should we use version 1.0.41-b instead of a later version&mdash;or should the dist-tag be moved to version 1.2.1?

**Comment by dsmilkov** [comment]
Also would be great to know the clang versions of the binaries in this package. Maybe mention them in the README.md. The clang-format installed via homebrew, for the same style (`google`), behaves differently than the clang-format in this package.

**Comment by mprobst** [comment]
I find @latest pointing at 1.2.1, maybe some caching went wrong or you accidentally looked at the local versions?

```
$ npm ls -r clang-format@latest
clang-format@1.2.1 /Users/martinprobst/lsrc/node-clang-format
```

@dsmilkov you can always get the clang-format version using `./bin/[arch]/clang-format --version`. I think that's easier than updating some README that's bound to go out of date. I've sent a PR to make that a bit more accessible.

**Comment by PsychicCat** [comment]
@mprobst I am also experiencing this issue. Installing latest gives us 1.0.41-c.

**Comment by mrfishy** [comment]
FYI: As of right now, this is what npmjs.com is showing as the version history:

![image](https://user-images.githubusercontent.com/2171125/38753694-d8e63306-3f24-11e8-85a3-0cdee2af8ad9.png)

**Comment by mprobst** [comment]
@vicb I see that you did something here, maybe you messed up the released versions?

@mrfishy @PsychicCat I think this might also be a misunderstanding wrt. `@latest` in npm. [According to the docs](https://docs.npmjs.com/cli/dist-tag), `@latest` is the last version that was published (which is 1.0.41-c apparently), not the highest version number version available (1.2.2). So this may be working as intended, and you might need to `npm install clang-format@1.2` or just `npm install clang-format`.

**Comment by mprobst** [comment]
I see, `npm install clang-format` actually takes `@latest`, not the highest version. Odd.

I've manually reset the `@latest` tag to `1.2.3` just now, so things should be back to working. @vicb something to keep in mind for the next release that we make on a branch, I guess.

**Comment by PsychicCat** [comment]
thanks @mprobst!
