### ISSUE TITLE
Not respecting ColumnLimit when formatting typescript file

### ISSUE THREAD

**Issue by mcgraphix** [angular/clang-format#56]
It seems that running clang-format against a typescript file with many imports on one line does not correctly format the line the correct length:

Steps to reproduce:
- create .clang-format file with this:
```
Language:        JavaScript
BasedOnStyle:    Google
ColumnLimit:     120
```
- create a typescript file with this in it:
```
import {AfterViewInit, ChangeDetectionStrategy, ChangeDetectorRef, Component, ElementRef, EventEmitter, forwardRef, HostListener, Input, OnChanges, OnDestroy, Output, SimpleChanges, ViewChild, ViewEncapsulation} from '@angular/core';
```
- run clang format with:
```
node_modules/clang-format/index.js -i -style="file" ./clang-test.ts
```
The import statement in the file is not formatted to respect the column limit.

**Comment by vicb** [comment]
IIRC you can choose to format imports as:

```
import {a, very, long, line, that, never, gets, wrapped} from 'somewhere';
```

or

```
import {
  each,
  symbol,
  on,
  one,
  line
} from 'somewhere';
```

Have you looked for closed issues already ?

**Comment by mcgraphix** [comment]
@vicb - I wouldn't mind using the one item per line. However,  In the first case, I would still expect it to respect the ColumnLimit when keeping all imports on one line. Something like this:

```
import {a, very, long, line, that, never,
   gets, wrapped} from 'somewhere';
```

**Comment by mprobst** [comment]
This is intentional, at least some users prefer the all-on-one-line style. clang-format has an explicit option to enable the wrapping. See `clang-format -dump-config` (it's `JavaScriptWrapImports`).
