### ISSUE TITLE
Configuration file(s) do(es) not support C++

### ISSUE THREAD

**Issue by vdegenne** [angular/clang-format#58]
If I add `JavaScript` in my `.clang-format`

```
BasedOnStyle:    Google
Language:           JavaScript
ColumnLimit:       100
```

and run this script,

```javascript
var gulp = require('gulp');
var clangFormat = require('clang-format');
var format = require('gulp-clang-format');


gulp.task('format', () => {
    return gulp.src(['manage'], { base: '.' })
	.pipe(format.format('file', clangFormat))
	.pipe(gulp.dest('.'));
});
```

the output is printing : 

```Configuration file(s) do(es) not support C++: /home/vdegenne/Gits/dotfiles/.clang-format```

## Versions

**node**  : 9.10.1
**gulp**   : 3.9.1
**clang-format** : 1.0.41-c

**Comment by mprobst** [comment]
You're getting this error because you are sending code through clang-format that it thinks is C++ - probably just because it falls back to C++ as a default. The culprit is this line:

```
    gulp.src(['manage'], { base: '.' })
```

It should be something like:

```
    gulp.src(['manage/**/*.ts', 'manage/**/*.js'], { base: '.' })
```

Alternatively, you can change your config to just generally use the `Google` style, but apply to all languages:

```
BasedOnStyle:    Google
---
Language:           JavaScript
ColumnLimit:       100
```

**Comment by mprobst** [comment]
I'll mark this issue as closed - if the above doesn't fix your problem, please re-open!

**Comment by gregbown** [comment]
I am getting this same error in VS-Code.  It occurs in any TypeScript file.  Using "typescript": "^2.9.x",
I have a [local .clang-format file](https://gist.github.com/gregbown/8b96293072565bd5b6cf659c8357dd68)
I also tried reducing the file to just declaring BasedOnStyle: Google

Windows 10
VS-CODE
Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Using [Clang Format plugin](https://github.com/xaverh/vscode-clang-format-provider)
Also posted within [that repo](https://github.com/xaverh/vscode-clang-format-provider/issues/67)

Appreciate any direction towards resolving this
Thank you
