### ISSUE TITLE
Semicolon required when not neeed

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/clang-format#6]
It seems like clang-format is requiring semicolons in places where those are not really needed, here is the example from the angular repo: https://github.com/angular/angular/blob/28022f472d5dbc231bb5c60da696744da40cf322/modules/angular2/src/facade/lang.ts#L45

To reproduce just remove the ; from the indicated line and see it failing.

Discussed with @mprobst

**Comment by mprobst** [comment]
Fixed by djasper in http://reviews.llvm.org/rL236978.
