### ISSUE TITLE
update clang-format binaries to latest version

### ISSUE THREAD

**Issue by 43081j** [angular/clang-format#67]
could someone let me know how you've previously updated the bins on here so i can pr an update? they haven't been updated in a _long_ time and now have a few problems with later js syntax (e.g. null coalesce).

happy to pr it if i understand the process you used last time, or if you can just sort it that works too.

**Comment by mprobst** [comment]
I'll need to compile new binaries and release a new version. I'll see that I get to it (the main difficulty is that I need a Windows machine...).

**Comment by mprobst** [comment]
I've just published version 1.4.0 based on the latest state, which should include support for `??` and `?.` (nullish coalescing operators).
