### ISSUE TITLE
Upgrade to Clang 12

### ISSUE THREAD

**Issue by benny-medflyt** [angular/clang-format#68]
The latest version of this npm package "clang-format' 1.4.0 comes with clang-format version 11.

Since then, Clang 12 has been released. It would be nice to have a new version of "clang-format" that gives us Clang 12.

Thank you

**Comment by quezak** [comment]
Any updates on this?

**Comment by mprobst** [comment]
I'm not sure I understand what you're trying to solve - clang-format
doesn't include Clang, so that version does not matter, does it?

**Comment by quezak** [comment]
> clang-format doesn't include Clang

I think it does, just the clang-format binary though: https://github.com/angular/clang-format/tree/master/bin/linux_x64

I didn't have clang installed locally and after installing this package `yarn clang-format` works, and reports it's using v11.0, so I think it's using the bundled executable. In particular, I then did install the whole clang package, had clang-format v12.0 on my system, but this js package still reported using v11.0:

```
>: clang-format --version
clang-format version 12.0.0

>: yarn clang-format --version
yarn run v1.22.10
$ /home/quezak/work/ramp-instant/node_modules/.bin/clang-format --version
clang-format NPM version 1.5.0 at /home/quezak/work/ramp-instant/node_modules/clang-format/index.js
clang-format version 11.0.0 (https://github.com/llvm/llvm-project.git 8a6b948eb59267736a34a5deace9c7d947c63492)
Done in 0.10s.
```

**Comment by H4M5TER** [comment]
Clang-format is a part of clang's extra tools.
Clang is a part of LLVM project.
There are official stable LLVM 12.0.1 now.
Check [here](https://releases.llvm.org/) for information.
Check [here](https://github.com/llvm/llvm-project/releases/tag/llvmorg-12.0.1) for downloads.

**Comment by xuelongmu** [comment]
I'd love to see an update to the latest version of clang-format, there are some new features that I'm looking to use in my projects. Current version is 14 now.

> I'm not sure I understand what you're trying to solve - clang-format doesn't include Clang, so that version does not matter, does it?

@mprobst The OP meant the clang-format 12, not clang itself :)

**Comment by mprobst** [comment]
Done in v1.7.0.

**Comment by mprobst** [comment]
(More precisely, we're cutting releases from head, so this is based on https://github.com/llvm/llvm-project/commit/596752863e27e6b4b89e34ecfcf5317a5bf46b52).

**Comment by xuelongmu** [comment]
Thank you @mprobst!
