### ISSUE TITLE
Incorrect formating of ||= logical or assignment 

### ISSUE THREAD

**Issue by juanpablius** [angular/clang-format#73]
When running clang format on JavaScript sentences:

let myVar;
myVar ||= 2;

clang-format transforms it to 

let myVar;
myVar || = 2;

It seems it doesn't understand the logical or assignemt from js
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment

**Comment by mprobst** [comment]
This was fixed in LLVM change [16212b8b3e4f](https://github.com/llvm/llvm-project/commit/16212b8b3e4f), about a year ago.

I believe this change should be included in recent releases of clang-format - maybe you're on an old version?

**Comment by mprobst** [comment]
Please reopen if you can repro with the latest version.
