### ISSUE TITLE
yarn.lock vs. package-lock.json

### ISSUE THREAD

**Issue by Trott** [angular/clang-format#75]
This has two competing lock files. Which one is the one to use? README seems to suggest that it's yarn.lock but it's 3 months older than the package-lock.json, so that suggests that maybe the package-lock.json is the one to use?

**Comment by mprobst** [comment]
I think we're using `npm ci`, and thus package-lock.json.

https://github.com/angular/clang-format/blob/master/.github/workflows/node.js.yml

Care to send a PR to update the docs and delete yarn.lock?

**Comment by Trott** [comment]
> Care to send a PR to update the docs and delete yarn.lock?

https://github.com/angular/clang-format/pull/76

No change to the docs. It turns out that the mentions of `yarn` were for end users who want to add clang-format to an existing project, not developers looking to install/debug the clang-format code itself.

**Comment by mprobst** [comment]
Thanks for the fix @Trott !
