### ISSUE TITLE
v1.7.0 does not work on intel macs

### ISSUE THREAD

**Issue by mikehardy** [angular/clang-format#78]
@mprobst the v1.7.0 mac executables are arm64:

```
mike@osxvm:~/work/Invertase/react-native-google-mobile-ads (@mikehardy/dependency-updates *) % cat node_modules/clang-format/package.json |grep version
  "version": "1.7.0",
mike@osxvm:~/work/Invertase/react-native-google-mobile-ads (@mikehardy/dependency-updates *) % file node_modules/clang-format/bin/darwin_x64/clang-format 
node_modules/clang-format/bin/darwin_x64/clang-format: Mach-O 64-bit executable arm64
```

If I `yarn add clang-format@1.6.0` things work for me on a non-M1 mac:

```

mike@osxvm:~/work/Invertase/react-native-google-mobile-ads (@mikehardy/dependency-updates *) % cat node_modules/clang-format/package.json |grep version
  "version": "1.6.0",
mike@osxvm:~/work/Invertase/react-native-google-mobile-ads (@mikehardy/dependency-updates *) % file node_modules/clang-format/bin/darwin_x64/clang-format 
node_modules/clang-format/bin/darwin_x64/clang-format: Mach-O 64-bit executable x86_64
```

I'm jealous of your M1 machine but do not have plans to purchase one myself for a little while. Is there a way to publish x86_64 builds for maximum compatibility until M1 compatibility has handle more thoroughly?

**Comment by mikehardy** [comment]
Thank you for the library by the way, I use it a lot and even patterned a java format off it in homage: https://github.com/invertase/nodejs-google-java-format/#inspiration :smile: :heart:

**Comment by mprobst** [comment]
@mikehardy I pushed 1.8.0 which should be back to `x86_64` (see 140dcf58048423922f88592176b48d8f2a2fa3f0).

**Comment by mikehardy** [comment]
Perfect! Confirmed working and I'm back to current for this dependency :-). Cheers
