### ISSUE TITLE
Request to update clang binaries

### ISSUE THREAD

**Issue by mattsoulanille** [angular/clang-format#79]
Hi. Would you be willing to update the clang binaries hosted in the npm package to fix https://github.com/llvm/llvm-project/issues/56797 ? Thanks in advance!

**Comment by mprobst** [comment]
We are actually planning to retire this package, as we're in the process of moving to prettier for our JS/TS formatting needs. As such, I do not plan to make anymore releases in the future, and will probably archive this repo.

**Comment by mattsoulanille** [comment]
Thanks for the update. I'll look into prettier instead.

**Comment by lumirlumir** [comment]
Hello. I've developed a new package to succeed `clang-format`, though the post was written some time ago. If you still need to use `clang-format`, please feel free to check it out.

https://github.com/lumirlumir/npm-clang-format-node
