### ISSUE TITLE
[Question]: public API (methods) first in classes

### ISSUE THREAD

**Issue by vicb** [angular/clang-format#8]
IMO having public API before private methods in class is nice.

Could this be automatically changed by clang-format ?
(an other question is do we really want to do this, open for debate).

**Comment by mprobst** [comment]
Moving code around (not just whitespace) is a pretty invasive change. I think that code authors often express intent or grouping by their code ordering, e.g. have a public method and then all its helpers, then have another public method and its helpers, and so on.

I remember tools like Eclipse used to support moving methods around in Java code, but I think that feature never got popular or commonly used, for exactly these reasons.

So I don't think moving around code like that is a good idea. On top of that, the current infrastructure/approach taken in clang-format would make this very hard to do.
