### ISSUE TITLE
clang-format: missing BraceWrapping configuration for multiline initialization list

### ISSUE THREAD

**Issue by alejandroclaro** [angular/clang-format#81]
It's not possible to adjust the position of braces when there is a multiple lines initialization list.

For example, in a code bases with Allman-like braces placement style. This

```c++
  std::vector<Bar> foo = 
  {
    makeBar(x, y, z),
    makeBar(u, v, w)
  };
  
  std::vector<int> baz = { 1, 2 };
```

is always transformed into this:

```c++
  std::vector<Bar> foo =  {
    makeBar(x, y, z),
    makeBar(u, v, w)
  };
  
  std::vector<int> baz = { 1, 2 };
```

It looks like there is a blocked PR related to this here: https://reviews.llvm.org/D91949

**Comment by alejandroclaro** [comment]
Sorry for this. I mistakenly reported the problem in the wrong repository

**Comment by Junjie-Fan** [comment]
> It's not possible to adjust the position of braces when there is a multiple lines initialization list.
> 
> For example, in a code bases with Allman-like braces placement style. This
> 
> ```c++
>   std::vector<Bar> foo = 
>   {
>     makeBar(x, y, z),
>     makeBar(u, v, w)
>   };
>   
>   std::vector<int> baz = { 1, 2 };
> ```
> 
> is always transformed into this:
> 
> ```c++
>   std::vector<Bar> foo =  {
>     makeBar(x, y, z),
>     makeBar(u, v, w)
>   };
>   
>   std::vector<int> baz = { 1, 2 };
> ```
> 
> It looks like there is a blocked PR related to this here: https://reviews.llvm.org/D91949

does some format config can solve this?
